---
  #宣告變數
  - shell: echo $(uname -s)-$(uname -m)
    register: os
  
  #安裝Docker-Compose
  - name: "下載Docker-Compose 1.25.0"
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-{{ os.stdout }}
      dest: /usr/local/bin/docker-compose
      mode: "755"
  - name: "設定Docker-Compose執行連結"
    file:
      src: /usr/local/bin/docker-compose
      dest: /usr/bin/docker-compose
      owner: root
      group: root
      state: link
      follow: yes